---
- name: Baseline de laboratoire
  hosts: web_lab
  become: true
  tasks:
    - name: Installer curl
      ansible.builtin.package:
        name: curl
        state: present

    - name: Créer le répertoire de preuve
      ansible.builtin.file:
        path: /etc/training
        state: directory
        mode: '0755'

    - name: Créer le fichier de preuve
      ansible.builtin.copy:
        content: |
          TP5 - Configuration appliquée par Ansible
          Hôte : {{ inventory_hostname }}
        dest: /etc/training/preuve.txt
        mode: '0644'
